name: annotation-software-dev
services:

  # TODO add backend and frontend services

  postgres:
    image: postgres:18
    container_name: ann-postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:?POSTGRES_USER is not set} -d ${POSTGRES_DB:?POSTGRES_DB is not set} || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: ann-pgbouncer
    restart: always
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: postgres
      DB_NAME: ${POSTGRES_DB}
      AUTH_TYPE: scram-sha-256 # remove/comment this line if using postgres:13 and lower
      POOL_MODE: transaction
      ADMIN_USERS: postgres,dbuser
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./docker-userlist.txt:/etc/pgbouncer/userlist.txt:ro
    ports:
      - "${PGBOUNCER_PORT}:5432"
    healthcheck:
      test: ['CMD', 'pg_isready', '-h', 'postgres']

  s3:
    image: minio/minio
    container_name: ann-s3
    restart: always
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_KEY}
      - MINIO_REGION_NAME=${AWS_REGION}
      - S3_BUCKET=${S3_BUCKET}
    ports:
      - "${AWS_ENDPOINT_PORT:-9000}:9000" # MinIO S3 Port
      - "${MINIO_CONSOLE_PORT:-9001}:9001" # MinIO Console Port
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - s3_data:/data
    entrypoint: >
      /bin/sh -c "
        minio server /data --console-address ':9001' &
        until mc alias set myminio http://localhost:9000 ${AWS_ACCESS_KEY} ${AWS_SECRET_KEY}; do
          echo 'Waiting for MinIO to be ready...'; sleep 2;
        done;
        mc mb myminio/${S3_BUCKET} || true;
        wait
      "

  redis:
    image: redis:latest
    container_name: ann-redis
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis-commander:
    image: rediscommander/redis-commander
    container_name: ann-redis-commander
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "${REDIS_COMMANDER_PORT:-8081}:8081"
    depends_on:
      - redis

  # Only for development to mock actual emails
  mailhog:
    image: mailhog/mailhog:latest
    container_name: ann-mailhog
    restart: always
    ports:
      - "${SMTP_PORT}:1025"   # SMTP port
      - "${MAILHOG_PORT:-9005}:8025"   # Web UI
    environment:
      MH_UI_BIND_ADDR: "0.0.0.0:8025"
      MH_API_BIND_ADDR: "0.0.0.0:8025"
      MH_SMTP_BIND_ADDR: "0.0.0.0:1025"


volumes:
  postgres_data:
  s3_data:
  redis_data:
